### ISSUE TITLE
Fetch PRs reviewed by the user between two specific dates from the Github API

### ISSUE THREAD

**Issue by hkedia321** [fossasia/scrum_helper#20]
**Actual Behaviour**

Currently, those Pull Requests are being fetched from the github API which are last commented on by any person between the specific dates:
```
"https://api.github.com/search/issues?q=commenter%3A"+githubUsername+"+org%3Afossasia+updated%3A"+startingDate+".."+endingDate+"&per_page=100"
```
So suppose if the person reviewed this PR 10 days ago, and some other person commented on it 2 days ago, it will appear in the "last week" search.

**Expected Behaviour**

Fetch the PRs which the person reviewed between two specific dates in any of the fossasia's repositories.

**Comment by panwarab** [comment]
you can use search api, something like this: `type:pr reviewed-by:${username} created:>=${date}`
date in YYYY-MM-DD format

**Comment by AdityaSrivast** [comment]
@hkedia321 Can I work on this issue please?

**Comment by hkedia321** [comment]
@AdityaSrivast yes sure, you can try
