### ISSUE TITLE
Porting this project in Firefox

### ISSUE THREAD

**Issue by vaibhavsingh97** [fossasia/scrum_helper#22]
**Actual Behaviour**
No extension present in firefox

**Expected Behaviour**
Firefox users should also take benefits of this extension

Please add a folder "firefox" into the root directory of the repository and develop the add-on here.

**Comment by hkedia321** [comment]
This can be done @vaibhavsingh97. We can have a different branch in this repo only, so that all the improvements can be easily made in both the versions

**Comment by vaibhavsingh97** [comment]
@hkedia321 I am up for this 👍

**Comment by hkedia321** [comment]
@vaibhavsingh97  I have created a branch `firefox_addon` for this purpose.

**Comment by championpaddler** [comment]
@vaibhavsingh97  Can I  work on this??

**Comment by hkedia321** [comment]
@sk9331657 Yes, please go ahead.
